version: '3.1'

services:
  hardcore_albattani:
    image: nginx
    build: .
    ports:
      - "8000:80"
      - "5500:5500"
    volumes:
      - 'C:\Users\znero\OneDrive\Dokumente\Github\Games\CreationOfMusic\server\data\conf:/etc/nginx/conf'  
      - 'C:\Users\znero\OneDrive\Dokumente\Github\Games\CreationOfMusic\server\data\www:/usr/share/nginx/html'  